# Generated by Django 4.2.7 on 2026-03-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('scheduled_date', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('template_path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_emails', to='leads.lead')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(max_length=100, unique=True)),
                ('caller_number', models.CharField(max_length=20)),
                ('call_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('call_notes', models.TextField(blank=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('call_type', models.CharField(choices=[('incoming', 'Incoming Call'), ('outgoing', 'Outgoing Call'), ('missed', 'Missed Call')], default='incoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='leads.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('keywords_extracted', models.CharField(blank=True, max_length=500)),
                ('conversion_likelihood', models.IntegerField(default=0, help_text='0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='leads.calllog')),
            ],
        ),
    ]
