# Generated by Django 6.0.3 on 2026-04-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_merge_website_lead_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website Leads'), ('call', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('google', 'Google Business'), ('referral', 'Referral'), ('telemarketing', 'Telemarketing'), ('social_media', 'Social Media'), ('other', 'Other')], default='website', max_length=20),
        ),
    ]
