# Generated by Django 6.0.3 on 2026-04-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleet',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='description',
        ),
        migrations.AddField(
            model_name='fleet',
            name='full_description',
            field=models.TextField(blank=True, help_text='Detailed description and best uses'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display on homepage'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order on homepage'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='short_description',
            field=models.TextField(default='', help_text='Brief description of the vehicle'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='vehicle_type',
            field=models.CharField(help_text='e.g., Sprinter High Roof, Bright Drop, Light Duty Box Truck', max_length=100),
        ),
    ]
