# Generated by Django 6.0.3 on 2026-04-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fleet_options_remove_fleet_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_address',
            field=models.TextField(default='828 Eastern Ave, Toronto, ON M4L 1A1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_phone',
            field=models.CharField(default='+1 (416) 710-0361', max_length=20),
        ),
    ]
