# Generated by Django 6.0.3 on 2026-04-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_site_address_phone_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='google_business_url',
            field=models.URLField(blank=True, default='https://maps.app.goo.gl/gEr1qAS8g4DRXYkNA?g_st=aw'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_email',
            field=models.EmailField(default='shahzaibsadiq256@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Eastern Logistics', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_phone',
            field=models.CharField(default='416-710-0361', max_length=20),
        ),
    ]
