# Generated by Django 6.0.3 on 2026-04-04 06:19

from django.db import migrations, models

NEW_ADDRESS = "828 Eastern Ave, Toronto, ON M4L 1A1, Canada"


def forwards(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    for s in SiteSettings.objects.all():
        s.site_address = NEW_ADDRESS
        s.save(update_fields=["site_address"])


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backfill_eastern_logistics_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_address',
            field=models.TextField(default='828 Eastern Ave, Toronto, ON M4L 1A1, Canada'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
