# Generated by Django 6.0.3 on 2026-04-04

from django.db import migrations, models

DEFAULT_HOURS = (
    "Monday–Sunday: 6 AM – 6 PM\n\n"
    "Holiday hours (e.g. Good Friday, Easter Sunday, Easter Monday) may differ—confirm on Google Maps or call us."
)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_site_address_canada_and_hours_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours',
            field=models.TextField(
                blank=True,
                default=DEFAULT_HOURS,
                help_text='Shown on the contact page. Use line breaks between lines.',
            ),
        ),
    ]
