# Generated by Django 6.0.3 on 2026-04-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_contact_phones_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_1',
            field=models.EmailField(blank=True, default='support@easternlogistics.app', help_text='First email address for contact page', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_2',
            field=models.EmailField(blank=True, default='info@easternlogistics.app', help_text='Second email address for contact page', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone_1',
            field=models.CharField(blank=True, default='+1 (416) 710-0361', help_text='First phone number for contact page. Format: +1 (XXX) XXX-XXXX', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone_2',
            field=models.CharField(blank=True, default='+1 (416) 555-1234', help_text='Second phone number for contact page. Format: +1 (XXX) XXX-XXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_emails',
            field=models.TextField(blank=True, default='', help_text='Deprecated - use contact_email_1 and contact_email_2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phones',
            field=models.TextField(blank=True, default='', help_text='Deprecated - use contact_phone_1 and contact_phone_2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_email',
            field=models.EmailField(default='support@easternlogistics.app', max_length=254),
        ),
    ]
