# Generated by Django 6.0.3 on 2026-04-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_individual_contact_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_emails',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_phones',
        ),
    ]
