# Generated by Django 6.0.3 on 2026-04-06 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_old_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='image',
            field=models.ImageField(blank=True, upload_to='fleet/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
    ]
